package monopoly.game.model;

public enum PropertyType {
    PROPERTY, RAILWAY_STATION, PAYMENT_FIELD, JAIL,
    CHANCE_FIELD, COMMUNITY_CHEST_FIELD, START_FIELD, JAIL_VISIT_FIELD,
    FREE_PARKING_FIELD, ELECTRIC_COMPANY, WATER_WORKS
}
