package monopoly.ux.module.event;

public enum UIEventType {
    ADD_GAME, ADD_LOG, ADD_MESSAGE_CHAT,
    ADD_PLAYER, REMOVE_GAME, REMOVE_PLAYER, REMOVE_PLAYER_TO, SET_GAMES, SET_HOME_NUM, SET_PLAYER_MONEY,
    SET_PLAYERS, SET_STEP_COUNTDOWN, SHOW_DIALOG, SHOW_DICE, START_GAME, SET_NEXT_STEP, SET_PROPERTY
}
